<?php

namespace AppBundle\Repository;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getForDay(\DateTime $date): array
    {
        return $this->getEntityManager()->createQuery("SELECT e FROM AppBundle:Event e
                           WHERE DATE_FORMAT(e.datetime,'%Y-%m-%d') = :datetime")->setParameter('datetime', $date->format('Y-m-d'))->getResult();
    }

    public function getForPeriod(\DateTime $start_date, \DateTime $end_date): array
    {
        return $this->getEntityManager()->createQuery('SELECT e FROM AppBundle:Event e
                           WHERE e.datetime BETWEEN :start_date AND :end_date')->setParameters(['start_date' => $start_date, 'end_date' => $end_date])->getResult();
    }
}
