<?php

namespace AppBundle\Repository;

/**
 * PonderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PonderRepository extends \Doctrine\ORM\EntityRepository
{
}
