<?php

namespace AppBundle\Repository;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getForPeriod(\DateTime $start_date, \DateTime $end_date): array
    {
        return $this->getEntityManager()->createQuery('SELECT t FROM AppBundle:Todo t
                           WHERE t.date BETWEEN :start_date AND :end_date')->setParameters([
            'start_date' => $start_date,
            'end_date' => $end_date
        ])->getResult();
    }
    public function getForDay(\DateTime $date): array
    {
        return $this->getEntityManager()->createQuery('SELECT t FROM AppBundle:Todo t
                           WHERE t.date = :date
                           OR  t.date < :date AND t.done = false')->setParameter('date', $date)->getResult();
    }
}
