<?php

namespace AppBundle\Repository;

/**
 * UntilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UntilRepository extends \Doctrine\ORM\EntityRepository
{
    public function getWeekTarget(): array
    {
        return $this->getEntityManager()->createQuery('SELECT u
                      FROM AppBundle:until u
                      WHERE u.deadline = DATE_ADD_MOD(CURDATE(), INTERVAL (8 - IF(DAYOFWEEK(CURDATE())=1, 8, DAYOFWEEK(CURDATE()))) DAY) ')->getResult();
    }
    public function getExpiring(int $days): array
    {
        return $this->getEntityManager()->createQuery('SELECT u 
                      FROM AppBundle:Until u
                      WHERE TO_DAYS(u.deadline) - TO_DAYS(CURRENT_DATE()) < :days
                      AND u.deadline > CURRENT_DATE()
                      AND NOT u.deadline = DATE_ADD_MOD(CURDATE(), INTERVAL (8 - IF(DAYOFWEEK(CURDATE())=1, 8, DAYOFWEEK(CURDATE()))) DAY)
                      ORDER BY u.deadline ASC')->setParameter('days', $days)->getResult();
    }
}
